import React from "react";

const WALL = 'WALL';
const BASE = 'BASE';
const ENTRY = 'ENTRY';
const PATH = 'PATH';
const PLAY = 'PLAY';


/// WHAT WE KNOW???
// We're doing simple.. Keep it simple..
// This is a one 2 one map; a dynamic map builder tool would be easy but out of scope
// the 'paths' the 'enemies' may travel must be 3 tiles in either x / y
//      The upper and lower paths are 2 SPACES
// PLAY and PATH may not be adjacent
// PLAY and BASE may not be adjacent
// It appears only one ENEMY may occupy a single PATH position at a time

/// WHAT WE DONT???
// moving the ENEMIES is actually an interesting problem the requires a clever solution..
//  At first we can assume every WAVE will travel on a fixed path to the BASE
//  When a BASE is destroyed with multiple enemies already going for that fixed position, the next step may be to back-
//   track to advance. In many cases the new path is likely to be diverge.
// The CS approach has me thinking "Dijkstra's" shortest path algorithm. But things change in computer science and I'm
// not sure how computationally expensive running this for every monster would be... We might try searching "Dijkstra's vs"
// on google and seeing if a better algorithm works in our use case... Were not exactly using a graph, and one monster may
// only occupy a space (i think) so handling that will not be fun.. Maybe it could all be hard coded...

/// STARTING FOCUS
// We can start with a single BASE objective
// Basic layout, I'd like to SPACES to scale to the full page?
//   This might require we have all the ENEMIES be SVG format so they scale..
//   loading this many svgs and moving dynamically them might cause perform issues; but we will find out.
// We can start with each CELL of the MATRIX (SPACE) is a different color; kyle is color blind so .... im actually not sure what to do
//        https://www.tableau.com/about/blog/examining-data-viz-rules-dont-use-red-green-together
//
// We can stick to the original color pallet and maybe keep some accessibility features in our mind
//

/// Projectile motion is an interesting one too ( ENEMY BOMBS )
//      if you google "linear splines" I think this math might help, but I could be overcomplicating too


// noinspection DuplicatedCode
const basicMap = [
    //                         5                             10                            15                            20                            25                            30                            35                            40                            45                            50                            55
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL,],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL,],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL,],
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL,],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL,],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL,],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, BASE, BASE, BASE, BASE, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, BASE, BASE, BASE, BASE, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, BASE, BASE, BASE, BASE, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, BASE, BASE, BASE, BASE, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, BASE, BASE, BASE, BASE, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL],
    [ENTRY, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, PLAY, WALL],
    [ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL,],
    //                         5                             10                            15                            20                            25                            30                            35                            40                            45                            50                            55
]


export default class OrbDefence extends React.Component<any, any> {
    constructor(props) {
        super(props);
        // we use this to make the card to appear after the page has been rendered
        this.state = {};
    }

    render() {
        return (
            <div>
                <h4>Error 404 - Page not Found</h4>
            </div>
        );
    }
}

